/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_pfa;



import java.sql.*;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author amine
 */
public class notes extends javax.swing.JFrame {
Connect x = new Connect();
  Connect y = new Connect();
   Statement st; 
   Statement sa;
 
    /**
     * Creates new form notes
     */
    public notes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabe = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabm = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabn = new javax.swing.JTable();
        cin = new javax.swing.JTextField();
        mat = new javax.swing.JTextField();
        not = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        re = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabb = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        moy = new javax.swing.JTable();
        m = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabe.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabe);

        tabm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabm.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabmAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabm);

        jButton1.setText("retour");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPane3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tabn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabnAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tabn);

        jButton2.setText("ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        re.setText("cin...");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });

        tabb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "moyene"
            }
        ));
        tabb.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabbAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(tabb);

        moy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "moyene"
            }
        ));
        jScrollPane5.setViewportView(moy);

        jButton3.setText("recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("refraiche");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        label1.setText("moyenne");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton4)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(72, 72, 72)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton4)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(not, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton5))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabeAncestorAdded

           String req = "select * from Etudiant";
        ResultSet rs;
        System.out.print(req);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabe.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}


        // TODO add your handling code here:
    }//GEN-LAST:event_tabeAncestorAdded

    private void tabmAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabmAncestorAdded
        // TODO add your handling code here:
        

    }//GEN-LAST:event_tabmAncestorAdded

    private void tabeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeMouseClicked
          int r = tabe.getSelectedRow();
          String ch = tabe.getModel().getValueAt(r, 0).toString();
        String req = "select m.ID_Matiere, m.lib , mf.coef from Etudiant e, matiere m , matiereformattion mf  where   e.idf = mf.idf and mf.ID_MATIERE = m.ID_MATIERE and e.cin = "+ch;
        ResultSet rs;

        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabm.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
     

        String reqt ="select e.cin , e.NOM,m.lib ,m.ID_matiere , n.note from Etudiant e, matiere m , notes n where e.cin = n.cin and m.ID_MATIERE = n.ID_MATIERE and e.cin = "+ ch;
        ResultSet rx;
      
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rx =  st.executeQuery(reqt);
            tabn.setModel(DbUtils.resultSetToTableModel(rx));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
        
        cin.setText(tabe.getModel().getValueAt(r, 0).toString());
        
        
         int s = tabe.getSelectedRow();
          String c = tabe.getModel().getValueAt(s, 0).toString();
        String reqi = "select m.lib from Etudiant e, formation m   where   e.Idf = m.idf and e.cin = "+c;
        ResultSet rxs;
        System.out.print(reqi);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rxs =  st.executeQuery(reqi);
          

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
        
        int xi = tabe.getSelectedRow();
       
        String reqq = "select  SUM ( n.note * mf.coef) from Etudiant e , matiereformattion mf , notes n    where   e.idf = mf.idf and mf.ID_MATIERE = n.ID_MATIERE and e.cin = n.cin and e.cin = "+ch;
        ResultSet rss;
        System.out.print(reqi);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rss =  st.executeQuery(reqq);
              tabb  .setModel(DbUtils.resultSetToTableModel(rss)); 
               
        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
        
         String raq = "select  SUM (mf.coef) from etudiant e ,  matiereformattion mf  where   mf.idf=e.idf and e.cin ="+ch;
        ResultSet rsx;
        System.out.print(raq);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rsx =  st.executeQuery(raq);
              moy.setModel(DbUtils.resultSetToTableModel(rsx)); 
                 float a = Float.valueOf (moy.getModel().getValueAt(0, 0).toString());
             float b = Float.valueOf (tabb.getModel().getValueAt(0, 0).toString());
           float o = b/a;
          String u = String.valueOf(o);
        m.setText( u );
        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
     
        // TODO add your handling code here:
    }//GEN-LAST:event_tabeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         index.n.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabnAncestorAdded
    int r = tabe.getSelectedRow();
          String ch = tabe.getModel().getValueAt(r, 0).toString();
        String req ="select e.cin , e.NOM,m.lib , n.note from Etudiant e, matiere m , notes n where e.cin = n.cin and m.ID_MATIERE = n.ID_MATIERE  ";
        ResultSet rs;
        System.out.print(req);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabn.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            System.out.println(e);} 
        
                       



        // TODO add your handling code here:
    }//GEN-LAST:event_tabnAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String reqt = "INSERT INTO notes VALUES ('"+mat.getText()+"','"+cin.getText()+"','"+not.getText()+"')";
        System.out.print(reqt);
        try{
          st=Connect.getcon().createStatement();
          st.executeQuery(reqt);
          JOptionPane.showMessageDialog(null,"ajouté avec succés");
        }
        catch(SQLException e )
            
        {System.out.println("");
            System.out.println(e);}
        int r = tabe.getSelectedRow();
          String ch = tabe.getModel().getValueAt(r, 0).toString();
        String req = "select m.ID_Matiere, m.lib , mf.coef from Etudiant e, matiere m , matiereformattion mf  where   e.idf = mf.idf and mf.ID_MATIERE = m.ID_MATIERE and e.cin = "+ch;
        ResultSet rs;
        System.out.print(req);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabm.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
        
      int ri = tabe.getSelectedRow();
          String chs = tabe.getModel().getValueAt(ri, 0).toString();
        String reqq = "select e.cin , e.NOM,m.lib ,m.ID_matiere , n.note from Etudiant e, matiere m , notes n where e.cin = n.cin and m.ID_MATIERE = n.ID_MATIERE and e.cin = "+ chs;
        ResultSet rsq;

        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rsq=  st.executeQuery(reqq);
            tabn.setModel(DbUtils.resultSetToTableModel(rsq));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollPane3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3AncestorAdded

    private void tabmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmMouseClicked
        // TODO add your handling code here:
         int r = tabm.getSelectedRow();
        mat.setText(tabm.getModel().getValueAt(r, 0).toString());
                
    }//GEN-LAST:event_tabmMouseClicked

    private void tabbAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabbAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabbAncestorAdded

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         String sh = re.getText();
        String req = "select * from Etudiant where cin = "+sh;
        ResultSet rs;
        System.out.print(req);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabe.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         String sh = re.getText();
        String req = "select * from Etudiant ";
        ResultSet rs;
        System.out.print(req);
        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabe.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         int r = tabn.getSelectedRow();
       String ci = tabn.getModel().getValueAt(r, 0).toString();
        String id = tabn.getModel().getValueAt(r, 3).toString();
       String reqt ="DELETE FROM notes where cin = "+ci+" and "+"ID_matiere = " + id;
         
       try { st=Connect.getcon().createStatement();
              st.executeQuery(reqt);
              JOptionPane.showMessageDialog(null,"supprimé avec succés");
            }
       catch(SQLException e )
       {
            System.out.print(e);
       }
       int re = tabe.getSelectedRow();
          String ch = tabe.getModel().getValueAt(re, 0).toString();
        String req = "select e.cin , e.NOM,m.lib ,m.ID_matiere , n.note from Etudiant e, matiere m , notes n where e.cin = n.cin and m.ID_MATIERE = n.ID_MATIERE and e.cin = "+ ch;
        ResultSet rs;

        try{
            st=Connect.getcon().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE );
            rs =  st.executeQuery(req);
            tabn.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(SQLException e )

        {System.out.println("");
            System.out.println(e);}
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private javax.swing.JTextField m;
    private javax.swing.JTextField mat;
    private javax.swing.JTable moy;
    private javax.swing.JTextField not;
    private javax.swing.JTextField re;
    private javax.swing.JTable tabb;
    private javax.swing.JTable tabe;
    private javax.swing.JTable tabm;
    private javax.swing.JTable tabn;
    // End of variables declaration//GEN-END:variables
}
